export default Object.freeze({
    SET_TASKS: "SET_TASKS",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    TURN_ON_OFF_LOADING: "TURN_ON_OFF_LOADING",
    DELETE_LOADER_SPINNER: "DELETE_LOADER_SPINNER",
    TOGGLE_OPEN_TASK_MODAL: "TOGGLE_OPEN_TASK_MODAL",
    ADD_TASK: "ADD_TASK",
    OPEN_TOGGLE_CONFIRM: "OPEN_TOGGLE_CONFIRM",
    TOGGLE_SELECTED_TASKS: "TOGGLE_SELECTED_TASKS",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    CHECK_ALL: "CHECK_ALL",
    SET_EDIT_TASK: "SET_EDIT_TASK",
    EDIT_TASK: "EDIT_TASK",
    SET_SINGLE_TASK: "SET_SINGLE_TASK",
    TOGGLE_SINGLE_TASK_EDIT: "TOGGLE_SINGLE_TASK_EDIT",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SUCCESS_MESSAGE: "SUCCESS_MESSAGE",
    CONTACT_FORM_CHANGE_HANDLER: "CONTACT_FORM_CHANGE_HANDLER"
})