export default Object.freeze({
    SET_TASKS: "SET_TASKS",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    TURN_ON_OFF_LOADING: "TURN_ON_OFF_LOADING",
    DELETE_LOADER_SPINNER: "DELETE_LOADER_SPINNER",
    TOGGLE_OPEN_TASK_MODAL: "TOGGLE_OPEN_TASK_MODAL",
    ADD_TASK: "ADD_TASK",
    OPEN_TOGGLE_CONFIRM: "OPEN_TOGGLE_CONFIRM",
    TOGGLE_SELECTED_TASKS: "TOGGLE_SELECTED_TASKS",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    CHECK_ALL: "CHECK_ALL",
    SET_EDIT_TASK: "SET_EDIT_TASK",
    EDIT_TASK: "EDIT_TASK"
})